/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: libp2p.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "libp2p.pb-c.h"
void   xdag__request__init
                     (Xdag__Request         *message)
{
  static const Xdag__Request init_value = XDAG__REQUEST__INIT;
  *message = init_value;
}
size_t xdag__request__get_packed_size
                     (const Xdag__Request *message)
{
  assert(message->base.descriptor == &xdag__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__request__pack
                     (const Xdag__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__request__pack_to_buffer
                     (const Xdag__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__Request *
       xdag__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__Request *)
     protobuf_c_message_unpack (&xdag__request__descriptor,
                                allocator, len, data);
}
void   xdag__request__free_unpacked
                     (Xdag__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__response__init
                     (Xdag__Response         *message)
{
  static const Xdag__Response init_value = XDAG__RESPONSE__INIT;
  *message = init_value;
}
size_t xdag__response__get_packed_size
                     (const Xdag__Response *message)
{
  assert(message->base.descriptor == &xdag__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__response__pack
                     (const Xdag__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__response__pack_to_buffer
                     (const Xdag__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__Response *
       xdag__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__Response *)
     protobuf_c_message_unpack (&xdag__response__descriptor,
                                allocator, len, data);
}
void   xdag__response__free_unpacked
                     (Xdag__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__identify_response__init
                     (Xdag__IdentifyResponse         *message)
{
  static const Xdag__IdentifyResponse init_value = XDAG__IDENTIFY_RESPONSE__INIT;
  *message = init_value;
}
size_t xdag__identify_response__get_packed_size
                     (const Xdag__IdentifyResponse *message)
{
  assert(message->base.descriptor == &xdag__identify_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__identify_response__pack
                     (const Xdag__IdentifyResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__identify_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__identify_response__pack_to_buffer
                     (const Xdag__IdentifyResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__identify_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__IdentifyResponse *
       xdag__identify_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__IdentifyResponse *)
     protobuf_c_message_unpack (&xdag__identify_response__descriptor,
                                allocator, len, data);
}
void   xdag__identify_response__free_unpacked
                     (Xdag__IdentifyResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__identify_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__connect_request__init
                     (Xdag__ConnectRequest         *message)
{
  static const Xdag__ConnectRequest init_value = XDAG__CONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t xdag__connect_request__get_packed_size
                     (const Xdag__ConnectRequest *message)
{
  assert(message->base.descriptor == &xdag__connect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__connect_request__pack
                     (const Xdag__ConnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__connect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__connect_request__pack_to_buffer
                     (const Xdag__ConnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__connect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__ConnectRequest *
       xdag__connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__ConnectRequest *)
     protobuf_c_message_unpack (&xdag__connect_request__descriptor,
                                allocator, len, data);
}
void   xdag__connect_request__free_unpacked
                     (Xdag__ConnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__connect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__stream_open_request__init
                     (Xdag__StreamOpenRequest         *message)
{
  static const Xdag__StreamOpenRequest init_value = XDAG__STREAM_OPEN_REQUEST__INIT;
  *message = init_value;
}
size_t xdag__stream_open_request__get_packed_size
                     (const Xdag__StreamOpenRequest *message)
{
  assert(message->base.descriptor == &xdag__stream_open_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__stream_open_request__pack
                     (const Xdag__StreamOpenRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__stream_open_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__stream_open_request__pack_to_buffer
                     (const Xdag__StreamOpenRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__stream_open_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__StreamOpenRequest *
       xdag__stream_open_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__StreamOpenRequest *)
     protobuf_c_message_unpack (&xdag__stream_open_request__descriptor,
                                allocator, len, data);
}
void   xdag__stream_open_request__free_unpacked
                     (Xdag__StreamOpenRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__stream_open_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__stream_handler_request__init
                     (Xdag__StreamHandlerRequest         *message)
{
  static const Xdag__StreamHandlerRequest init_value = XDAG__STREAM_HANDLER_REQUEST__INIT;
  *message = init_value;
}
size_t xdag__stream_handler_request__get_packed_size
                     (const Xdag__StreamHandlerRequest *message)
{
  assert(message->base.descriptor == &xdag__stream_handler_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__stream_handler_request__pack
                     (const Xdag__StreamHandlerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__stream_handler_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__stream_handler_request__pack_to_buffer
                     (const Xdag__StreamHandlerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__stream_handler_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__StreamHandlerRequest *
       xdag__stream_handler_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__StreamHandlerRequest *)
     protobuf_c_message_unpack (&xdag__stream_handler_request__descriptor,
                                allocator, len, data);
}
void   xdag__stream_handler_request__free_unpacked
                     (Xdag__StreamHandlerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__stream_handler_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__error_response__init
                     (Xdag__ErrorResponse         *message)
{
  static const Xdag__ErrorResponse init_value = XDAG__ERROR_RESPONSE__INIT;
  *message = init_value;
}
size_t xdag__error_response__get_packed_size
                     (const Xdag__ErrorResponse *message)
{
  assert(message->base.descriptor == &xdag__error_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__error_response__pack
                     (const Xdag__ErrorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__error_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__error_response__pack_to_buffer
                     (const Xdag__ErrorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__error_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__ErrorResponse *
       xdag__error_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__ErrorResponse *)
     protobuf_c_message_unpack (&xdag__error_response__descriptor,
                                allocator, len, data);
}
void   xdag__error_response__free_unpacked
                     (Xdag__ErrorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__error_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__stream_info__init
                     (Xdag__StreamInfo         *message)
{
  static const Xdag__StreamInfo init_value = XDAG__STREAM_INFO__INIT;
  *message = init_value;
}
size_t xdag__stream_info__get_packed_size
                     (const Xdag__StreamInfo *message)
{
  assert(message->base.descriptor == &xdag__stream_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__stream_info__pack
                     (const Xdag__StreamInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__stream_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__stream_info__pack_to_buffer
                     (const Xdag__StreamInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__stream_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__StreamInfo *
       xdag__stream_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__StreamInfo *)
     protobuf_c_message_unpack (&xdag__stream_info__descriptor,
                                allocator, len, data);
}
void   xdag__stream_info__free_unpacked
                     (Xdag__StreamInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__stream_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__dhtrequest__init
                     (Xdag__DHTRequest         *message)
{
  static const Xdag__DHTRequest init_value = XDAG__DHTREQUEST__INIT;
  *message = init_value;
}
size_t xdag__dhtrequest__get_packed_size
                     (const Xdag__DHTRequest *message)
{
  assert(message->base.descriptor == &xdag__dhtrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__dhtrequest__pack
                     (const Xdag__DHTRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__dhtrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__dhtrequest__pack_to_buffer
                     (const Xdag__DHTRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__dhtrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__DHTRequest *
       xdag__dhtrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__DHTRequest *)
     protobuf_c_message_unpack (&xdag__dhtrequest__descriptor,
                                allocator, len, data);
}
void   xdag__dhtrequest__free_unpacked
                     (Xdag__DHTRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__dhtrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__dhtresponse__init
                     (Xdag__DHTResponse         *message)
{
  static const Xdag__DHTResponse init_value = XDAG__DHTRESPONSE__INIT;
  *message = init_value;
}
size_t xdag__dhtresponse__get_packed_size
                     (const Xdag__DHTResponse *message)
{
  assert(message->base.descriptor == &xdag__dhtresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__dhtresponse__pack
                     (const Xdag__DHTResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__dhtresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__dhtresponse__pack_to_buffer
                     (const Xdag__DHTResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__dhtresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__DHTResponse *
       xdag__dhtresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__DHTResponse *)
     protobuf_c_message_unpack (&xdag__dhtresponse__descriptor,
                                allocator, len, data);
}
void   xdag__dhtresponse__free_unpacked
                     (Xdag__DHTResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__dhtresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__peer_info__init
                     (Xdag__PeerInfo         *message)
{
  static const Xdag__PeerInfo init_value = XDAG__PEER_INFO__INIT;
  *message = init_value;
}
size_t xdag__peer_info__get_packed_size
                     (const Xdag__PeerInfo *message)
{
  assert(message->base.descriptor == &xdag__peer_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__peer_info__pack
                     (const Xdag__PeerInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__peer_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__peer_info__pack_to_buffer
                     (const Xdag__PeerInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__peer_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__PeerInfo *
       xdag__peer_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__PeerInfo *)
     protobuf_c_message_unpack (&xdag__peer_info__descriptor,
                                allocator, len, data);
}
void   xdag__peer_info__free_unpacked
                     (Xdag__PeerInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__peer_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__conn_manager_request__init
                     (Xdag__ConnManagerRequest         *message)
{
  static const Xdag__ConnManagerRequest init_value = XDAG__CONN_MANAGER_REQUEST__INIT;
  *message = init_value;
}
size_t xdag__conn_manager_request__get_packed_size
                     (const Xdag__ConnManagerRequest *message)
{
  assert(message->base.descriptor == &xdag__conn_manager_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__conn_manager_request__pack
                     (const Xdag__ConnManagerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__conn_manager_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__conn_manager_request__pack_to_buffer
                     (const Xdag__ConnManagerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__conn_manager_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__ConnManagerRequest *
       xdag__conn_manager_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__ConnManagerRequest *)
     protobuf_c_message_unpack (&xdag__conn_manager_request__descriptor,
                                allocator, len, data);
}
void   xdag__conn_manager_request__free_unpacked
                     (Xdag__ConnManagerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__conn_manager_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__disconnect_request__init
                     (Xdag__DisconnectRequest         *message)
{
  static const Xdag__DisconnectRequest init_value = XDAG__DISCONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t xdag__disconnect_request__get_packed_size
                     (const Xdag__DisconnectRequest *message)
{
  assert(message->base.descriptor == &xdag__disconnect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__disconnect_request__pack
                     (const Xdag__DisconnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__disconnect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__disconnect_request__pack_to_buffer
                     (const Xdag__DisconnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__disconnect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__DisconnectRequest *
       xdag__disconnect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__DisconnectRequest *)
     protobuf_c_message_unpack (&xdag__disconnect_request__descriptor,
                                allocator, len, data);
}
void   xdag__disconnect_request__free_unpacked
                     (Xdag__DisconnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__disconnect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__psrequest__init
                     (Xdag__PSRequest         *message)
{
  static const Xdag__PSRequest init_value = XDAG__PSREQUEST__INIT;
  *message = init_value;
}
size_t xdag__psrequest__get_packed_size
                     (const Xdag__PSRequest *message)
{
  assert(message->base.descriptor == &xdag__psrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__psrequest__pack
                     (const Xdag__PSRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__psrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__psrequest__pack_to_buffer
                     (const Xdag__PSRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__psrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__PSRequest *
       xdag__psrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__PSRequest *)
     protobuf_c_message_unpack (&xdag__psrequest__descriptor,
                                allocator, len, data);
}
void   xdag__psrequest__free_unpacked
                     (Xdag__PSRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__psrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__psmessage__init
                     (Xdag__PSMessage         *message)
{
  static const Xdag__PSMessage init_value = XDAG__PSMESSAGE__INIT;
  *message = init_value;
}
size_t xdag__psmessage__get_packed_size
                     (const Xdag__PSMessage *message)
{
  assert(message->base.descriptor == &xdag__psmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__psmessage__pack
                     (const Xdag__PSMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__psmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__psmessage__pack_to_buffer
                     (const Xdag__PSMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__psmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__PSMessage *
       xdag__psmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__PSMessage *)
     protobuf_c_message_unpack (&xdag__psmessage__descriptor,
                                allocator, len, data);
}
void   xdag__psmessage__free_unpacked
                     (Xdag__PSMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__psmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xdag__psresponse__init
                     (Xdag__PSResponse         *message)
{
  static const Xdag__PSResponse init_value = XDAG__PSRESPONSE__INIT;
  *message = init_value;
}
size_t xdag__psresponse__get_packed_size
                     (const Xdag__PSResponse *message)
{
  assert(message->base.descriptor == &xdag__psresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xdag__psresponse__pack
                     (const Xdag__PSResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xdag__psresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xdag__psresponse__pack_to_buffer
                     (const Xdag__PSResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xdag__psresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Xdag__PSResponse *
       xdag__psresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Xdag__PSResponse *)
     protobuf_c_message_unpack (&xdag__psresponse__descriptor,
                                allocator, len, data);
}
void   xdag__psresponse__free_unpacked
                     (Xdag__PSResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &xdag__psresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue xdag__request__type__enum_values_by_number[9] =
{
  { "IDENTIFY", "XDAG__REQUEST__TYPE__IDENTIFY", 0 },
  { "CONNECT", "XDAG__REQUEST__TYPE__CONNECT", 1 },
  { "STREAM_OPEN", "XDAG__REQUEST__TYPE__STREAM_OPEN", 2 },
  { "STREAM_HANDLER", "XDAG__REQUEST__TYPE__STREAM_HANDLER", 3 },
  { "DHT", "XDAG__REQUEST__TYPE__DHT", 4 },
  { "LIST_PEERS", "XDAG__REQUEST__TYPE__LIST_PEERS", 5 },
  { "CONNMANAGER", "XDAG__REQUEST__TYPE__CONNMANAGER", 6 },
  { "DISCONNECT", "XDAG__REQUEST__TYPE__DISCONNECT", 7 },
  { "PUBSUB", "XDAG__REQUEST__TYPE__PUBSUB", 8 },
};
static const ProtobufCIntRange xdag__request__type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex xdag__request__type__enum_values_by_name[9] =
{
  { "CONNECT", 1 },
  { "CONNMANAGER", 6 },
  { "DHT", 4 },
  { "DISCONNECT", 7 },
  { "IDENTIFY", 0 },
  { "LIST_PEERS", 5 },
  { "PUBSUB", 8 },
  { "STREAM_HANDLER", 3 },
  { "STREAM_OPEN", 2 },
};
const ProtobufCEnumDescriptor xdag__request__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xdag.Request.Type",
  "Type",
  "Xdag__Request__Type",
  "xdag",
  9,
  xdag__request__type__enum_values_by_number,
  9,
  xdag__request__type__enum_values_by_name,
  1,
  xdag__request__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor xdag__request__field_descriptors[8] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, type),
    &xdag__request__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connect",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, connect),
    &xdag__connect_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streamOpen",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, streamopen),
    &xdag__stream_open_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streamHandler",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, streamhandler),
    &xdag__stream_handler_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dht",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, dht),
    &xdag__dhtrequest__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connManager",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, connmanager),
    &xdag__conn_manager_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnect",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, disconnect),
    &xdag__disconnect_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pubsub",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Request, pubsub),
    &xdag__psrequest__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__request__field_indices_by_name[] = {
  5,   /* field[5] = connManager */
  1,   /* field[1] = connect */
  4,   /* field[4] = dht */
  6,   /* field[6] = disconnect */
  7,   /* field[7] = pubsub */
  3,   /* field[3] = streamHandler */
  2,   /* field[2] = streamOpen */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange xdag__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor xdag__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.Request",
  "Request",
  "Xdag__Request",
  "xdag",
  sizeof(Xdag__Request),
  8,
  xdag__request__field_descriptors,
  xdag__request__field_indices_by_name,
  1,  xdag__request__number_ranges,
  (ProtobufCMessageInit) xdag__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue xdag__response__type__enum_values_by_number[2] =
{
  { "OK", "XDAG__RESPONSE__TYPE__OK", 0 },
  { "ERROR", "XDAG__RESPONSE__TYPE__ERROR", 1 },
};
static const ProtobufCIntRange xdag__response__type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex xdag__response__type__enum_values_by_name[2] =
{
  { "ERROR", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor xdag__response__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xdag.Response.Type",
  "Type",
  "Xdag__Response__Type",
  "xdag",
  2,
  xdag__response__type__enum_values_by_number,
  2,
  xdag__response__type__enum_values_by_name,
  1,
  xdag__response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor xdag__response__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Xdag__Response, type),
    &xdag__response__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Response, error),
    &xdag__error_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streamInfo",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Response, streaminfo),
    &xdag__stream_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identify",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Response, identify),
    &xdag__identify_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dht",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Response, dht),
    &xdag__dhtresponse__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peers",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Xdag__Response, n_peers),
    offsetof(Xdag__Response, peers),
    &xdag__peer_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pubsub",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__Response, pubsub),
    &xdag__psresponse__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__response__field_indices_by_name[] = {
  4,   /* field[4] = dht */
  1,   /* field[1] = error */
  3,   /* field[3] = identify */
  5,   /* field[5] = peers */
  6,   /* field[6] = pubsub */
  2,   /* field[2] = streamInfo */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange xdag__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor xdag__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.Response",
  "Response",
  "Xdag__Response",
  "xdag",
  sizeof(Xdag__Response),
  7,
  xdag__response__field_descriptors,
  xdag__response__field_indices_by_name,
  1,  xdag__response__number_ranges,
  (ProtobufCMessageInit) xdag__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__identify_response__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__IdentifyResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addrs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__IdentifyResponse, n_addrs),
    offsetof(Xdag__IdentifyResponse, addrs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__identify_response__field_indices_by_name[] = {
  1,   /* field[1] = addrs */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange xdag__identify_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor xdag__identify_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.IdentifyResponse",
  "IdentifyResponse",
  "Xdag__IdentifyResponse",
  "xdag",
  sizeof(Xdag__IdentifyResponse),
  2,
  xdag__identify_response__field_descriptors,
  xdag__identify_response__field_indices_by_name,
  1,  xdag__identify_response__number_ranges,
  (ProtobufCMessageInit) xdag__identify_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__connect_request__field_descriptors[3] =
{
  {
    "peer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__ConnectRequest, peer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addrs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__ConnectRequest, n_addrs),
    offsetof(Xdag__ConnectRequest, addrs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Xdag__ConnectRequest, has_timeout),
    offsetof(Xdag__ConnectRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__connect_request__field_indices_by_name[] = {
  1,   /* field[1] = addrs */
  0,   /* field[0] = peer */
  2,   /* field[2] = timeout */
};
static const ProtobufCIntRange xdag__connect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor xdag__connect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.ConnectRequest",
  "ConnectRequest",
  "Xdag__ConnectRequest",
  "xdag",
  sizeof(Xdag__ConnectRequest),
  3,
  xdag__connect_request__field_descriptors,
  xdag__connect_request__field_indices_by_name,
  1,  xdag__connect_request__number_ranges,
  (ProtobufCMessageInit) xdag__connect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__stream_open_request__field_descriptors[3] =
{
  {
    "peer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__StreamOpenRequest, peer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Xdag__StreamOpenRequest, n_proto),
    offsetof(Xdag__StreamOpenRequest, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Xdag__StreamOpenRequest, has_timeout),
    offsetof(Xdag__StreamOpenRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__stream_open_request__field_indices_by_name[] = {
  0,   /* field[0] = peer */
  1,   /* field[1] = proto */
  2,   /* field[2] = timeout */
};
static const ProtobufCIntRange xdag__stream_open_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor xdag__stream_open_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.StreamOpenRequest",
  "StreamOpenRequest",
  "Xdag__StreamOpenRequest",
  "xdag",
  sizeof(Xdag__StreamOpenRequest),
  3,
  xdag__stream_open_request__field_descriptors,
  xdag__stream_open_request__field_indices_by_name,
  1,  xdag__stream_open_request__number_ranges,
  (ProtobufCMessageInit) xdag__stream_open_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__stream_handler_request__field_descriptors[2] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__StreamHandlerRequest, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Xdag__StreamHandlerRequest, n_proto),
    offsetof(Xdag__StreamHandlerRequest, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__stream_handler_request__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = proto */
};
static const ProtobufCIntRange xdag__stream_handler_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor xdag__stream_handler_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.StreamHandlerRequest",
  "StreamHandlerRequest",
  "Xdag__StreamHandlerRequest",
  "xdag",
  sizeof(Xdag__StreamHandlerRequest),
  2,
  xdag__stream_handler_request__field_descriptors,
  xdag__stream_handler_request__field_indices_by_name,
  1,  xdag__stream_handler_request__number_ranges,
  (ProtobufCMessageInit) xdag__stream_handler_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__error_response__field_descriptors[1] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Xdag__ErrorResponse, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__error_response__field_indices_by_name[] = {
  0,   /* field[0] = msg */
};
static const ProtobufCIntRange xdag__error_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor xdag__error_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.ErrorResponse",
  "ErrorResponse",
  "Xdag__ErrorResponse",
  "xdag",
  sizeof(Xdag__ErrorResponse),
  1,
  xdag__error_response__field_descriptors,
  xdag__error_response__field_indices_by_name,
  1,  xdag__error_response__number_ranges,
  (ProtobufCMessageInit) xdag__error_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__stream_info__field_descriptors[3] =
{
  {
    "peer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__StreamInfo, peer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__StreamInfo, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Xdag__StreamInfo, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__stream_info__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = peer */
  2,   /* field[2] = proto */
};
static const ProtobufCIntRange xdag__stream_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor xdag__stream_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.StreamInfo",
  "StreamInfo",
  "Xdag__StreamInfo",
  "xdag",
  sizeof(Xdag__StreamInfo),
  3,
  xdag__stream_info__field_descriptors,
  xdag__stream_info__field_indices_by_name,
  1,  xdag__stream_info__number_ranges,
  (ProtobufCMessageInit) xdag__stream_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue xdag__dhtrequest__type__enum_values_by_number[9] =
{
  { "FIND_PEER", "XDAG__DHTREQUEST__TYPE__FIND_PEER", 0 },
  { "FIND_PEERS_CONNECTED_TO_PEER", "XDAG__DHTREQUEST__TYPE__FIND_PEERS_CONNECTED_TO_PEER", 1 },
  { "FIND_PROVIDERS", "XDAG__DHTREQUEST__TYPE__FIND_PROVIDERS", 2 },
  { "GET_CLOSEST_PEERS", "XDAG__DHTREQUEST__TYPE__GET_CLOSEST_PEERS", 3 },
  { "GET_PUBLIC_KEY", "XDAG__DHTREQUEST__TYPE__GET_PUBLIC_KEY", 4 },
  { "GET_VALUE", "XDAG__DHTREQUEST__TYPE__GET_VALUE", 5 },
  { "SEARCH_VALUE", "XDAG__DHTREQUEST__TYPE__SEARCH_VALUE", 6 },
  { "PUT_VALUE", "XDAG__DHTREQUEST__TYPE__PUT_VALUE", 7 },
  { "PROVIDE", "XDAG__DHTREQUEST__TYPE__PROVIDE", 8 },
};
static const ProtobufCIntRange xdag__dhtrequest__type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex xdag__dhtrequest__type__enum_values_by_name[9] =
{
  { "FIND_PEER", 0 },
  { "FIND_PEERS_CONNECTED_TO_PEER", 1 },
  { "FIND_PROVIDERS", 2 },
  { "GET_CLOSEST_PEERS", 3 },
  { "GET_PUBLIC_KEY", 4 },
  { "GET_VALUE", 5 },
  { "PROVIDE", 8 },
  { "PUT_VALUE", 7 },
  { "SEARCH_VALUE", 6 },
};
const ProtobufCEnumDescriptor xdag__dhtrequest__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xdag.DHTRequest.Type",
  "Type",
  "Xdag__DHTRequest__Type",
  "xdag",
  9,
  xdag__dhtrequest__type__enum_values_by_number,
  9,
  xdag__dhtrequest__type__enum_values_by_name,
  1,
  xdag__dhtrequest__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor xdag__dhtrequest__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Xdag__DHTRequest, type),
    &xdag__dhtrequest__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__DHTRequest, has_peer),
    offsetof(Xdag__DHTRequest, peer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__DHTRequest, has_cid),
    offsetof(Xdag__DHTRequest, cid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__DHTRequest, has_key),
    offsetof(Xdag__DHTRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__DHTRequest, has_value),
    offsetof(Xdag__DHTRequest, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Xdag__DHTRequest, has_count),
    offsetof(Xdag__DHTRequest, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Xdag__DHTRequest, has_timeout),
    offsetof(Xdag__DHTRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__dhtrequest__field_indices_by_name[] = {
  2,   /* field[2] = cid */
  5,   /* field[5] = count */
  3,   /* field[3] = key */
  1,   /* field[1] = peer */
  6,   /* field[6] = timeout */
  0,   /* field[0] = type */
  4,   /* field[4] = value */
};
static const ProtobufCIntRange xdag__dhtrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor xdag__dhtrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.DHTRequest",
  "DHTRequest",
  "Xdag__DHTRequest",
  "xdag",
  sizeof(Xdag__DHTRequest),
  7,
  xdag__dhtrequest__field_descriptors,
  xdag__dhtrequest__field_indices_by_name,
  1,  xdag__dhtrequest__number_ranges,
  (ProtobufCMessageInit) xdag__dhtrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue xdag__dhtresponse__type__enum_values_by_number[3] =
{
  { "BEGIN", "XDAG__DHTRESPONSE__TYPE__BEGIN", 0 },
  { "VALUE", "XDAG__DHTRESPONSE__TYPE__VALUE", 1 },
  { "END", "XDAG__DHTRESPONSE__TYPE__END", 2 },
};
static const ProtobufCIntRange xdag__dhtresponse__type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex xdag__dhtresponse__type__enum_values_by_name[3] =
{
  { "BEGIN", 0 },
  { "END", 2 },
  { "VALUE", 1 },
};
const ProtobufCEnumDescriptor xdag__dhtresponse__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xdag.DHTResponse.Type",
  "Type",
  "Xdag__DHTResponse__Type",
  "xdag",
  3,
  xdag__dhtresponse__type__enum_values_by_number,
  3,
  xdag__dhtresponse__type__enum_values_by_name,
  1,
  xdag__dhtresponse__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor xdag__dhtresponse__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Xdag__DHTResponse, type),
    &xdag__dhtresponse__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Xdag__DHTResponse, peer),
    &xdag__peer_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__DHTResponse, has_value),
    offsetof(Xdag__DHTResponse, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__dhtresponse__field_indices_by_name[] = {
  1,   /* field[1] = peer */
  0,   /* field[0] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange xdag__dhtresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor xdag__dhtresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.DHTResponse",
  "DHTResponse",
  "Xdag__DHTResponse",
  "xdag",
  sizeof(Xdag__DHTResponse),
  3,
  xdag__dhtresponse__field_descriptors,
  xdag__dhtresponse__field_indices_by_name,
  1,  xdag__dhtresponse__number_ranges,
  (ProtobufCMessageInit) xdag__dhtresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__peer_info__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__PeerInfo, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addrs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PeerInfo, n_addrs),
    offsetof(Xdag__PeerInfo, addrs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__peer_info__field_indices_by_name[] = {
  1,   /* field[1] = addrs */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange xdag__peer_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor xdag__peer_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.PeerInfo",
  "PeerInfo",
  "Xdag__PeerInfo",
  "xdag",
  sizeof(Xdag__PeerInfo),
  2,
  xdag__peer_info__field_descriptors,
  xdag__peer_info__field_indices_by_name,
  1,  xdag__peer_info__number_ranges,
  (ProtobufCMessageInit) xdag__peer_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue xdag__conn_manager_request__type__enum_values_by_number[3] =
{
  { "TAG_PEER", "XDAG__CONN_MANAGER_REQUEST__TYPE__TAG_PEER", 0 },
  { "UNTAG_PEER", "XDAG__CONN_MANAGER_REQUEST__TYPE__UNTAG_PEER", 1 },
  { "TRIM", "XDAG__CONN_MANAGER_REQUEST__TYPE__TRIM", 2 },
};
static const ProtobufCIntRange xdag__conn_manager_request__type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex xdag__conn_manager_request__type__enum_values_by_name[3] =
{
  { "TAG_PEER", 0 },
  { "TRIM", 2 },
  { "UNTAG_PEER", 1 },
};
const ProtobufCEnumDescriptor xdag__conn_manager_request__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xdag.ConnManagerRequest.Type",
  "Type",
  "Xdag__ConnManagerRequest__Type",
  "xdag",
  3,
  xdag__conn_manager_request__type__enum_values_by_number,
  3,
  xdag__conn_manager_request__type__enum_values_by_name,
  1,
  xdag__conn_manager_request__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor xdag__conn_manager_request__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Xdag__ConnManagerRequest, type),
    &xdag__conn_manager_request__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__ConnManagerRequest, has_peer),
    offsetof(Xdag__ConnManagerRequest, peer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Xdag__ConnManagerRequest, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Xdag__ConnManagerRequest, has_weight),
    offsetof(Xdag__ConnManagerRequest, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__conn_manager_request__field_indices_by_name[] = {
  1,   /* field[1] = peer */
  2,   /* field[2] = tag */
  0,   /* field[0] = type */
  3,   /* field[3] = weight */
};
static const ProtobufCIntRange xdag__conn_manager_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor xdag__conn_manager_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.ConnManagerRequest",
  "ConnManagerRequest",
  "Xdag__ConnManagerRequest",
  "xdag",
  sizeof(Xdag__ConnManagerRequest),
  4,
  xdag__conn_manager_request__field_descriptors,
  xdag__conn_manager_request__field_indices_by_name,
  1,  xdag__conn_manager_request__number_ranges,
  (ProtobufCMessageInit) xdag__conn_manager_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__disconnect_request__field_descriptors[1] =
{
  {
    "peer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Xdag__DisconnectRequest, peer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__disconnect_request__field_indices_by_name[] = {
  0,   /* field[0] = peer */
};
static const ProtobufCIntRange xdag__disconnect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor xdag__disconnect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.DisconnectRequest",
  "DisconnectRequest",
  "Xdag__DisconnectRequest",
  "xdag",
  sizeof(Xdag__DisconnectRequest),
  1,
  xdag__disconnect_request__field_descriptors,
  xdag__disconnect_request__field_indices_by_name,
  1,  xdag__disconnect_request__number_ranges,
  (ProtobufCMessageInit) xdag__disconnect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue xdag__psrequest__type__enum_values_by_number[4] =
{
  { "GET_TOPICS", "XDAG__PSREQUEST__TYPE__GET_TOPICS", 0 },
  { "LIST_PEERS", "XDAG__PSREQUEST__TYPE__LIST_PEERS", 1 },
  { "PUBLISH", "XDAG__PSREQUEST__TYPE__PUBLISH", 2 },
  { "SUBSCRIBE", "XDAG__PSREQUEST__TYPE__SUBSCRIBE", 3 },
};
static const ProtobufCIntRange xdag__psrequest__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex xdag__psrequest__type__enum_values_by_name[4] =
{
  { "GET_TOPICS", 0 },
  { "LIST_PEERS", 1 },
  { "PUBLISH", 2 },
  { "SUBSCRIBE", 3 },
};
const ProtobufCEnumDescriptor xdag__psrequest__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "xdag.PSRequest.Type",
  "Type",
  "Xdag__PSRequest__Type",
  "xdag",
  4,
  xdag__psrequest__type__enum_values_by_number,
  4,
  xdag__psrequest__type__enum_values_by_name,
  1,
  xdag__psrequest__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor xdag__psrequest__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Xdag__PSRequest, type),
    &xdag__psrequest__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "topic",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Xdag__PSRequest, topic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSRequest, has_data),
    offsetof(Xdag__PSRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__psrequest__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = topic */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange xdag__psrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor xdag__psrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.PSRequest",
  "PSRequest",
  "Xdag__PSRequest",
  "xdag",
  sizeof(Xdag__PSRequest),
  3,
  xdag__psrequest__field_descriptors,
  xdag__psrequest__field_indices_by_name,
  1,  xdag__psrequest__number_ranges,
  (ProtobufCMessageInit) xdag__psrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__psmessage__field_descriptors[6] =
{
  {
    "from",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSMessage, has_from),
    offsetof(Xdag__PSMessage, from),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSMessage, has_data),
    offsetof(Xdag__PSMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seqno",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSMessage, has_seqno),
    offsetof(Xdag__PSMessage, seqno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "topicIDs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Xdag__PSMessage, n_topicids),
    offsetof(Xdag__PSMessage, topicids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSMessage, has_signature),
    offsetof(Xdag__PSMessage, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSMessage, has_key),
    offsetof(Xdag__PSMessage, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__psmessage__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = from */
  5,   /* field[5] = key */
  2,   /* field[2] = seqno */
  4,   /* field[4] = signature */
  3,   /* field[3] = topicIDs */
};
static const ProtobufCIntRange xdag__psmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor xdag__psmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.PSMessage",
  "PSMessage",
  "Xdag__PSMessage",
  "xdag",
  sizeof(Xdag__PSMessage),
  6,
  xdag__psmessage__field_descriptors,
  xdag__psmessage__field_indices_by_name,
  1,  xdag__psmessage__number_ranges,
  (ProtobufCMessageInit) xdag__psmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xdag__psresponse__field_descriptors[2] =
{
  {
    "topics",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Xdag__PSResponse, n_topics),
    offsetof(Xdag__PSResponse, topics),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peerIDs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Xdag__PSResponse, n_peerids),
    offsetof(Xdag__PSResponse, peerids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xdag__psresponse__field_indices_by_name[] = {
  1,   /* field[1] = peerIDs */
  0,   /* field[0] = topics */
};
static const ProtobufCIntRange xdag__psresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor xdag__psresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xdag.PSResponse",
  "PSResponse",
  "Xdag__PSResponse",
  "xdag",
  sizeof(Xdag__PSResponse),
  2,
  xdag__psresponse__field_descriptors,
  xdag__psresponse__field_indices_by_name,
  1,  xdag__psresponse__number_ranges,
  (ProtobufCMessageInit) xdag__psresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
